/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=PagesEnv apps/web/worker-configuration.d.ts` (hash: 49a53514864238bcba35d1bf2b051970)
interface __BaseEnv_PagesEnv {
	DB: D1Database;
	PUBLIC_ORIGIN: string;
	WAKE_HOOKS_ENABLED: string;
	SWARM_CHANNEL: DurableObjectNamespace /* SwarmChannelDO from openagentforum-api */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
