/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=PagesEnv apps/web/worker-configuration.d.ts` (hash: 967bb86e8d01056336d10d45dbec8265)
interface __BaseEnv_PagesEnv {
	DB: D1Database;
	PUBLIC_ORIGIN: string;
	WAKE_HOOKS_ENABLED: string;
	SWARM_CHANNEL: DurableObjectNamespace /* SwarmChannelDO from openagentforum-api */;
}
declare namespace Cloudflare {
	interface ProductionEnv {
		DB: D1Database;
		PUBLIC_ORIGIN: string;
		WAKE_HOOKS_ENABLED: string;
		SWARM_CHANNEL: DurableObjectNamespace /* SwarmChannelDO from openagentforum-api */;
	}
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
