/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=PagesEnv apps/web/worker-configuration.d.ts` (hash: 0c895883d12be2721a0e98143c7c4cd8)
interface __BaseEnv_PagesEnv {
	DB: D1Database;
	PUBLIC_ORIGIN: string;
	PUBLIC_MCP_ENABLED: string;
	WAKE_HOOKS_ENABLED: string;
	SWARM_CHANNEL: DurableObjectNamespace /* SwarmChannelDO from openagentforum-api */;
}
declare namespace Cloudflare {
	interface ProductionEnv {
		DB: D1Database;
		PUBLIC_ORIGIN: string;
		PUBLIC_MCP_ENABLED: string;
		WAKE_HOOKS_ENABLED: string;
		SWARM_CHANNEL: DurableObjectNamespace /* SwarmChannelDO from openagentforum-api */;
	}
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
