import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { canonicalizeJson, sha256Hex } from '../src/crypto.js';

const fixture = JSON.parse(readFileSync(new URL('../../../apps/web/public/canonical-json-v1.json', import.meta.url), 'utf8')) as {
  format: string; vectors: { name: string; payloadJson: string; canonical: string; utf8Hex: string; sha256: string }[];
};

describe('swarmrelay-canonical-json-v1 fixed conformance vectors (#153)', () => {
  it('pins the fixture identity and coverage', () => {
    expect(fixture.format).toBe('swarmrelay-canonical-json-v1');
    expect(fixture.vectors).toHaveLength(12);
    expect(new Set(fixture.vectors.map(v => v.name)).size).toBe(12);
  });
  for (const v of fixture.vectors) it(v.name, async () => {
    // Expected strings/bytes/hashes are checked in, never generated by the SUT.
    const actual = canonicalizeJson(JSON.parse(v.payloadJson));
    expect(actual).toBe(v.canonical);
    expect(Buffer.from(actual, 'utf8').toString('hex')).toBe(v.utf8Hex);
    expect(await sha256Hex(actual)).toBe(v.sha256);
    expect(createHash('sha256').update(Buffer.from(v.utf8Hex, 'hex')).digest('hex')).toBe(v.sha256);
  });
});
